### PR TITLE
Bump version 0.5.0

### PR DESCRIPTION
**Pull request by mkundu1**

### CODE REVIEW

**Comment by dnwillia-work** [comment]
@RobPasMue and @mkundu1.  I don't think the changes from #101 ever made it back into the main branch so the VTK dependency is not there.

**Comment by mkundu1** [comment]
> @RobPasMue and @mkundu1. I don't think the changes from #101 ever made it back into the main branch so the VTK dependency is not right on main. Probably that should be put back onto main before this.

@dnwillia-work Comparing main and release-0.4 bracnh, VTK version looks to be fine in main branch:

https://github.com/pyansys/pyfluent-visualization/blob/main/pyproject.toml#L29

https://github.com/pyansys/pyfluent-visualization/blob/release/0.4/pyproject.toml#L29

**Comment by dnwillia-work** [comment]
> > @RobPasMue and @mkundu1. I don't think the changes from #101 ever made it back into the main branch so the VTK dependency is not right on main. Probably that should be put back onto main before this.
> 
> @dnwillia-work Comparing main and release-0.4, VTK version looks to be fine in the main branch:
> 
> https://github.com/pyansys/pyfluent-visualization/blob/main/pyproject.toml#L29
> 
> https://github.com/pyansys/pyfluent-visualization/blob/release/0.4/pyproject.toml#L29

Yeah, ok, I see.  I guess I got confused by the fact that the main branch seems to have a release number that is before the latest package we have released. 

https://github.com/pyansys/pyfluent-visualization/blob/4eba449e5c6dcd8346af2ceef959eea95e480a88/pyproject.toml#L8

Is it supposed to be like that?

**Review by prmukherj — APPROVED** [review]

**Review by dnwillia-work — APPROVED** [review]

**Review by prmukherj — APPROVED** [review]

**Comment by RobPasMue** [comment]
Looks like the release branch and the main branch are both updated regarding the VTK change. I think it's just that the main branch has defined its version as 0.4.0. I recommend you to always "version" your main branch one minor version ahead of your release branch and with the "dev" version in patch. For example:

* Latest release: ``0.4.1``
* Version in main branch: ``0.5.dev0``

This is a typical version naming convention throughout the PyAnsys libraries

**Comment by mkundu1** [comment]
Consumed these changes in the intermittent dev release (#111)

**Pull request closed without merging**
